# Generated by Django 6.0 on 2025-12-28 14:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/blocks/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('text_color', models.CharField(blank=True, max_length=30)),
                ('font_family', models.CharField(blank=True, max_length=100)),
                ('font_size', models.CharField(blank=True, max_length=30)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='articles.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
